apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.250.1.200-10.250.1.230 #docker network inspect -f '{{.IPAM.Config}}' kind
