apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: runenv
        value: #RUNENV#
      - name: externaldomain
        value: #RUNENV#.#DOMAIN#
      - name: internaldomain
        value: int-#RUNENV#.#DOMAIN#
      - name: iprange
        value: #IPRANGE#
      - name: registry
        value: #REGISTRY#
    path: argocd-applications
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

