kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-b
networking:
  podSubnet: "10.242.0.0/16"
  serviceSubnet: "10.94.0.0/16"
  ipFamily: ipv4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./shared/multi-b
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./shared/multi-b
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./shared/multi-b
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./shared/multi-b
    containerPath: /data
