#kubectl create secret generic --dry-run=client -o yaml -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"  > secret.yaml
apiVersion: v1
data:
  secretkey: aUdNS1UxUVhRV2xRUGlWV2Z2dHhqbis4TVFDK1BkbVlxbmFINVZUVUVKeUFWVnk4Q09OQUpwUnlqaGRsb3MyTwpjK0J5VTByandHRlJSNnRaencyQmFWdEFlUm1MUXVrY0R0eWlJWmhOUGk2eXphaEU4bWlPb0JTMXZzYlFoWGROCndWSW5HYlE1S0l5S0JHVXFQd2NjOXQvdlZ5SENBRFFnRUg4U3FVYjByRDg9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
