apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd-yaml/metallb
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
