apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCWzSdVeZ+J0HJk7JIL7WA7+40fxQCVwKizpPPNSJehpB2Ew+kGjOkDon+aEzN+jSnYm9kx2EbRAUdvyag4ZHWCWwUKY6sy1MhaNWbins4H+7PN4hpP5uENzIO4hClP89CWA1dVr32ubgq+G/WVL+Zu0K2JKTwrLdICRdElaB2/mzgbloIHb4skaFct0CtzPypybWwhtJ3qM7ltMIILF4YYRrvGQSri76ghj7mtuTP0ZBlQz8aMUnZcLMwMBpsxeyTFszIJPEq0B2VQyFZAlTI976ms5X/w8CZeikSaCwr0so56WfnFnFx6obD3CRiGwbpJTm293QRvlBoqMWjAOu/440A8j5nAiAMIqg7RObIi+e+enlebzYyZiBgLDVszOS+K0/FzOOLqBqfiWMq0nn2FSTE+ePVxIovoVJZfehll7XqoJYrNiee50wkgejMc40UlSGxJOmSDS98zCOxBOnc9D+tqLOmsZ6NUrWNwrxe3dvPWw69nuWwKR6ZdrF099Jqik47jwQdzSWgSNr8OmY9Z49q7r9nIXP6OVG9sbRvSQuZ2wzpYWOoltcrz0XtODlA+UhgColeBlzP2hHmayeA7mVUTmv82cwEtf5YbCQytIdPbqzANG7DRxhM1Qlae0mPUNXg6F8aMLZ0mt3F8iqzxFQXmb82XW0zWG8+AUpc2IzGR6mwP473CqRMyyokgH8vAj/KsHbFHuBrQNqFTHzVT+oyAs2SfEQeUQgho7rM=
    admin.passwordMtime: AgCkIeRlWCD3BecakWaiK6yV5mTLR4YV0THf4ZcTE1NS0w737R+zxmEWWWIIjX5isNpUIzKbaMubakuirM8Ir57eQTfJDIzDZg6Q/sQVrvPGZtEUj3Zdw3eGohDBbq/didkiDrNdACoNRmFjRNRQZ7gwjjutme4mKuZiZ5I5d1AnKI0d/o/icsa1TnCMelvgwlNFeResXO3nkd05N+klkoLW3VOho5vY+d/jIWD/3tn2KTyvujON5ODEd0NRWWzrFIWja8lw6/MXz1ye+VsLM1UHkyos9TX715ztUP350mIy94g1nyBLP6bo2oR2KgC55/TsluRdKyxG0757NP3WCHCMk0EZY+ReXVIghvnA5oPgl5DL/pQYi5ycnoHvqav7Y0Yykho9KzgH+4kYRxKeVnX56eOMzBzhCsVq1v79oGeaSKqpPZWb5QUm3TvLoMkXZK0hgk6rLUatXM00kwDZWZtTzY7BdClXZDvAV+Diq3b+nV5m7WEXJ620NraveHgvqoAtFVSGay0oRI+G1WcAmMQUvMPxV+BETiD5dtAs1mvVc2t17/3YlB890SiZiS+54QUOouL9MylxFkKO1zk0YdH66Rf6lmu32fktBvA/UDYwFHhv10+KMcXvFUmdUEYZ1XE1K84K7sDrymj52l5xbb/Umen6ihPy8pbw80a4A4NIL0KxCkLzrY8NL/TgFuQa3V0/5D0KV2x5hjH+msO6H8k97sWuMQ==
    server.secretkey: AgAaUF5nUb97LuXJFWjycIcJT9Ie63ioFkd4pfrdiDy1QsEay8+4n/4Mitzc26St0OylOktKa04BvfXiJy8y+0s9Ylh4tPUbkLXvEm92wZdEykW1+fGcKtWOcksSnnIV0GLXbWeV1keo78oBI0xvkv+f5nHFIL9bAoxIkt6IJ4j3rQ5/Hw2ZdE/jcYh3+RbfumrBjNj3WRFK7iTeTEsmrs67eg8BvZPUnwNAFC85X6t9AGXoE4PTjGWopLO2ceKLcs1Sw33aGzIfn4ckiBaaxT/nT9XpckHWj5hIl7qpefVbdTZo56bff524PRXWwzvuvNitjJ/a/QUAg/iWDzWYp0MoJvwwSzHK1g3Lf2gdT/xN+U/tX0gchOdWx8a79oTFEXe5zEXKOJeuHpKMJMe5FjqqKkTNNFLBWX18Jy5jGl4O6+uO67iPhUthHGN1y4JXx1CRH0KgzQAz2VYktcOP2cO9pFa1YiyZCSlsB5+yfBLIz4oIZszgN2d4XaOlLvO8TuWImkVgckJeAPVHnwcXPWLHsLUKa76B6m+EzfRw4ujqwWn2k1LtYOwjy0f+xyQXU7KEgLzfOZYBrRL0u/4V8htrtFCnD2eyvTgL8tLLeAQCyDujtbNjHTwR08UAQ+nhfmeZYpF8aU6KnLmaEX/VJwfCcahI/tBKAN0GRCPhzcAYthUKCUJFhQE/6fjr3Oo3IbhSCsoJofA3u+QuIdIzRriLdDKBVy8WFohycOaaguHS/4AOtKoCJU1cjQh+2A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque

