apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: certbot-ext
  namespace: certbot-ext
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCXU0jCW+fbzq9eje0DpuSXeZogczmHcnulKDgx6x51PL0xdNnZ1xMwEtfc8uWJYMIdXo4g76ifcqmfitlcLVun6P6cVjcplv1rR+Rr4SPwAnuQ0x0LXrQz1BeTU7+vwxeyKwJnj+RMds5Hg+lqXsjg5mO8NvchKB0gvevooDuDnb1eHEptb+TZkv6oaA1XqcR8kMLRgvOY/1vhvPhQ35gMtmcgI4W5eBX+OByGZ+rlGZMUYOc39Weh2Rd/RlUTE5inHAW5pA+9dgs4OFGaY5XfPsY6MaSkOckXGmv9NXi7v53yIczNmXvxYDCnCq81ntbnlevLy9qfbvmh4AAwOfDnb+nN1lQuWYbzsEOfiZ8nyocJyBd6ohKKUjFxJgga2Dlz1+/7Iol/lEYo0AsFMXB+gWlN8xbefKLmpYSVSMfD60KmiS22hlA8339tWAqqPMvZmy4fiQK38EZQErgBgfjP3ssC3gEZQ4E68R60yR98CCEf9M+UIA3vYeB1Lpp7byyEHbRu70PDqTs/MvzRpuogVeC+aDlUDq7xlaYjpGsO91EjKx1Qv7w6Rc/PTC1TqrpCnnaXkV4KyGKDCCr8fTF+lfRrVqTXdW6AklFAAUSzbgL+Cj48QH+J6bYMck++IWGf2WH9Q5lbfa3ucdoE7q7eaU4Wem/pasDsATE9/DKLRp44yEOTlzUoV6TJtjzunvYOnJqER3lmh9gvFtwSbTYy7LizBg==
    AWS_SECRET_ACCESS_KEY: AgBeALCi+fPlP/fjyj9zeK3yCMlMmc4GW1d8gPLjNzGJuKYnwRLug5E30VlxeBic4RGroggA4xQmg70HeucPB0UqgQAx5bonMmH/scvWS4XQB4Db1jeB2tVG0+rvuN1osOLa6NYLkklBQGTNzg19LHoPE3Y78cJ3b8/i+cdQ2oOpaNS+8mJaicW/7jDrnzCpZ7GOAHWGzroyWea9iwyXvTf98qvNfjji3alB/SYxezv2Wot5ruagY3O58Bmgwavmuy8imZYGs0dqGk1VnAAMkTNNq8uUayxAzU6WW+M6xxL0Ge4h5jIRrdYqMU50V3If/TZEcM93qVFYZWL+EC9IEoYkwIt8rFdDHV2FeRM+1pCWhHFOKTaXlGePrywNPLD5CD2csKZOMTdY2Dp6uiZT3gyet2bv9t58qbR0UScfIjbwvW9GyX3BpBMD8VdzunzmHZtaRlWs8rXGfSgbHVfvyRkkjfdRP6OrELQ9w3KOFB6AFYzpcY3c4i302tJ0g5jcnDdO0fy9hro/+4LSxloujnI7EzCWPatY8R/ZLMnV6622PBPvcf1Yp+srbUWXrbsZuTzHYJzbQ/YcjKgzQVzpAi7lkOQzV+l96Mus2glNp494R3Pv23I421KUPBCCrLsMaRjwng3rnPfAbDHuSCUGy1k6AvrOfV+/a/1qFey09fEgPq+eoiF9wyt4b6W0WVOfRoxMGsmhz+8QlHm16WfaSqvHStuHg/O5FNo2JKzgbzUuJNm+Cczurhgn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: certbot-ext
      namespace: certbot-ext

