apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA2hMNaIgPsnH2mOKvBUIkPZyRr6JoWH/ixRN1CL1CgErltrGsM3OOE80ZZDs2MM6ZMCjsjiRJAyoj/j47jfuOrnDvNZoHSunRpokQXUsfRy5roNX7DmAVmpqD5b/szIYVNv8RUlvQpvXb7fdDwdFVYyHWZHUYC2LLp/aI9NRX442GjOJTM2li8m/6ZBtxJ9iqXEidXb5AIMvm9ONhUlVnqoGXEjYfBHppwAAGbAh4N+2jbX3T71SoIF/GlM6Of5N0FMd1ILtaAWPoA3xMQ+EGCHIF/FkrwMv04D9egBPcExzrYqHZ0YUxv0ccaArdtpUd2KIPsJW+Mau4vHpmYqbuWRJS4U5V6ogrmwWJm+1nHymviqMyhEhNgAQzJWK1nbteRhbYpX3X4sMsMwR7Whs1bxyPeGg18zo3Pb1wElPInUi/l0edPfzHHoSeaW6u2a8vK3qNfGq4/k7U8oQ5Wavhlgsjd93KZ1iAVCt9Yy6lAHQ874VavhXcKwQOYMODF+kF3AamALl802MmbsKkk4cdlFjIZY8d31JZ4hQptcLLA4LMY59PodDD6eXrVEGTelUretATz5Lf/+QHxMbWstChbx7A4Ehtq3rc9JKh5ZG0NyTe615FPz5vAZ2snTsA/oOXnidj45kJcbQvdA8A7cfxKlXqq3HkzyOzleOezinUA2PXAJ2sL4/xCXAP1wXZMBaahBeVbGII8GsO+ClkuG68oetgTTQ==
    AWS_SECRET_ACCESS_KEY: AgCsYJaaWZ8DPmlMJLyXIn8ND8KAciaA2ioZZRQLJnmp4ruZ/OaZZKzc4wNkows+i4FE2fzUajYpauEoqnVY6ezADzFQp3thCZer9rGqHWvzTxOhzoJlEnmcH7g/c0+DMVu46SBHtgiZuQkMJWlB39fh7W4FGSu3Vcj/xE+TG6kbEusz+A+HsXU+fGB+6pb9RRT6K26tdpg01rgEkfl6ukaNKIu7Tux0SbmmqfQckUB8PzyrMZ6/3Dtw7EQwrLHKHMHiqoRfhGNTvvSfACnXLmp8TQRYHHlWUo6iqGAKD7KzfVcsGJjYxBvhA5lM3Btj2q+o+tDz3Qdwve5v2TEkcfxQwX/NXK1cFcYGVj97StRJ+6ci6JsKlWRVcl9AOs2Mo9ZB2u3Ki/lwVEy+Ws6BPCvVMsclsJgyLaD0/Nsp2BgmKEFbSykRfv2BRmtMO1edWQvpP43ve8qwRdcT/eBdrmYwjgfkZwZTxA0vY8WDnFK617gm2pkqMKbpyrf2i5k5ANBNoYFF+nvZU+FdAM/HgM37mgKE7733Vdz9qCMeVYDFqBxl87GW9DOy/Z+Kh2Rgjb+f2PD7dbeZVoiM0nU2GEJNsRKpHO0KSGcuFFPL8wYxZ+J55GUUff5YRDgzI8Yq0MwqDoAnn5JbXwCQxiFWJmkZqgNIEtIVBOv9nZ/mQnGtyIVi/9B3L4bSLR3QYTiNGbUq7ALOtunYGntFyGjPFx4E/OsDkZ9Jr0EVBa5gKDVeIruYZdpCkWa5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns

