apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certbot-ext
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: certbot-ext
  project: default
  source:
    path: argocd-yaml/certbot
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      releaseName: certbot-ext
      parameters:
      - name: domain
        value: {{ .Values.externaldomain }}
      - name: secretnamespace
        value: {{ .Values.secretnamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
