apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entigo-training-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:      
    path: argocd-yaml/entigo-training-application
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: runenv
        value: {{ .Values.runenv }}
      - name: externaldomain
        value: {{ .Values.externaldomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
