apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  project: default
  source:
    path: argocd-yaml/external-dns
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      releaseName: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
