apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-int
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy-int
  project: default
  source:
    path: argocd-yaml/haproxy
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      releaseName: haproxy-int
      parameters:
      - name: route53domain
        value: {{ .Values.internaldomain }}
      - name: httpport
        value: "8080"
      - name: httpsport
        value: "8443"
      - name: monitoringport
        value: "1025"
      - name: isdefault
        value: "true"
      - name: certsecret
        value: "certbot-int/ssl"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
