apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ext
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy-ext
  project: default
  source:
    path: argocd-yaml/haproxy
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      releaseName: haproxy-ext
      parameters:
      - name: route53domain
        value: {{ .Values.externaldomain }}
      - name: httpport
        value: "80"
      - name: httpsport
        value: "443"
      - name: monitoringport
        value: "1026"
      - name: isdefault
        value: "false"
      - name: certsecret
        value: "certbot-ext/ssl"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
