apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-controller
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: argocd-yaml/sealed-secret-controller
    repoURL: https://github.com/martivo/kind-lab-thesis.git
    targetRevision: HEAD
    helm:
      releaseName: sealed-secret-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
