apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBJF1xmfbAZFJATfAX2XQrgUNYPEbnSEHIJNG9IvwODh0ly9gs2keh0J+y6iJEHLdzopTIv1FszHtpCyU8PH5OBChTzYxyb2NHxX31RZbYhCnqkKEkbgKsQqQiffyw8omnZKrOfDs0olmHg0i7QEqrKAdTZwRLfS0BfLjQ5K+7X6gGAFwFJ5vAN1h1/cZWPNXgIRIcqIvw3ScY7oSvW9mDwDWzlvS4QsUQd3cegKIuD2JpDgcuyF/Sp395stK+CPO9xBaqFEt1UgtVA2oTVLVgnkGI7okBKPtvi0RZKDpOOBFQoJSIcBL6g0l7qpPZrLs9AkWFkwF3XIe4DNF3j18RrPCa6ghXAVG/k0RjLLO9hCbTCqgNp38gYlrVYGV9Egi4i5j4XYdRiF9Z36dkJ+++DYG1ZYV0YkxU1M0olFJPueEz3zugT+InYGLc+C9y7pX4wVR3I05tg7k/vxd4THqF2BjF4gOO/F5OvmfltjBv7qZ9XDlx2IDCeSXKgrV5c9+v/Og6iuVfmTnpJ4JAugJQgiaHnv3kDJ0Zn2kFeETTMMDr9DE7ZHP5op5NPWxcUnNegRE8bNL91bkb2AQMKnoSklimr6N7aW1pDbGf3IPXJ5oLQGzLKn+DbDFea5wk67xi5E2G7Gb3kHqxrYMuWhQCAVPvBAkKqdxGj3QNsmu1o/OZpQ0jx3Mh0yo7HH9piTZE2TLBsUglcaDahkafm2PPolvBR0Q==
    AWS_SECRET_ACCESS_KEY: AgDF6201yqvazP7sqDPDS/XZ5dfgl0OaectgwiEUFjLrXj8sg7xMvPsl4pKrxpqleqjbbfnpN6EOajCdks2Q8ss2nAGCaywlI+gc7rriQ+neh0/1HKdEZQHdj2maUshfaO6/0QBeWXA7MX2YnGHi6AlhBWkW0eCmv56FlZJwPO1c5mSx7CLNJdX0rVw726cI7AEjtRMK901MMdEyKctkC4jY3wbwOGh2LSKkaplUy7+1Wrja66+bQthVdjlpPwaGU971jZMbg3eY66Aca25uJ1ZDWtZS6vPv+mrQTQXkY8zh1UkXTBqnZxJwzFoUlxh0pTJ02wh4QVVSo9evm6cHgbKV7pTlS5Qo4EqqOja4s8f2OVJ8/umqQ87G5rLClNy1V4QgFO4WpAPe12CqQmbcScATUkWyJfIwjS9ejjOycysuKIcVnhxuZRLYlbDDcfqsy7th4CcxL6ZQvojY/m7wtlcM/4/+THGOe6PgL8/EVTd/J6AzlMpGUT7Tyr7TqwqDNoxRuFfxPjcW/h1kR6bSubDhGNAoQ54LCzEJoHE7IKOCwQqxOQShL19N61DyO86Jllw74Jffu6r7rkouRJCawM2uK+aXbNWnH9oMkD65X8OY+RSVou6snVQl9vftSQDz2sBVSvzwLZw4UULLTzMngtV1r0oQiKCHHL5N0cALEglroE4lnqBjZxK7Jagthe+Rku4C4YMyEPv6z2myuym2TkLiKjNId7H44RLlQW6zpNRdTWRN+OxewlLl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns

