
runenv: single

web:
  replicaCount: 2
  image: entigolabs/entigo-kubernetes-training:web-v1
  
api:
  replicaCount: 2
  image: entigolabs/entigo-kubernetes-training:api-v1
  redisHost: redis

redis:
  image: redis:6
